-- MySQL Script generated by MySQL Workbench
-- Sat Oct  1 23:15:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vehicleApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vehicleApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehicleApp` DEFAULT CHARACTER SET utf8 ;
USE `vehicleApp` ;

-- -----------------------------------------------------
-- Table `vehicleApp`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicleApp`.`Vehicle` (
  `idVehicle` VARCHAR(15) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `doors` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL,
  UNIQUE INDEX `idVehicle_UNIQUE` (`idVehicle` ASC) VISIBLE,
  PRIMARY KEY (`idVehicle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehicleApp`.`Register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehicleApp`.`Register` (
  `idRegister` VARCHAR(40) NOT NULL,
  `Vehicle_vin` VARCHAR(15) NOT NULL,
  `start_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idRegister`),
  UNIQUE INDEX `idRegister_UNIQUE` (`idRegister` ASC) VISIBLE,
  INDEX `fk_Register_Vehicle1_idx` (`Vehicle_vin` ASC) VISIBLE,
  CONSTRAINT `fk_Register_Vehicle1`
    FOREIGN KEY (`Vehicle_vin`)
    REFERENCES `vehicleApp`.`Vehicle` (`idVehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
